#!/usr/bin/env python3
"""
analyze.py — Day 4. End-to-end: .eml (or bundle) -> LLM verdict -> report.

Every run appends one JSON line to logs/runs.jsonl containing the prompt
version, model, latency, token counts, repair history, schema problems, the
grounding check, and the raw model output. That log is the raw material for
the Day 6 evaluation — do not delete it, and do not let it be the thing you
wish you had captured after a 200-email batch run.

Usage:
    python3 scripts/analyze.py samples/03_phish_credential.eml
    python3 scripts/analyze.py out/03_phish_credential.json --from-bundle
    python3 scripts/analyze.py --dir samples/ --report-dir reports/
    python3 scripts/analyze.py --check          # connectivity only
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from eml_parser import parse_eml                       # noqa: E402
from grounding_check import check_indicators           # noqa: E402
from llm_client import DEFAULT_HOST, DEFAULT_MODEL, OllamaClient, OllamaError  # noqa: E402
from prompt_builder import (build_prompt_input, budget_report,  # noqa: E402
                            load_system_prompt, render_user_message)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_PATH = os.path.join(ROOT, "logs", "runs.jsonl")

VERDICT_ICON = {"phishing": "[PHISHING]", "suspicious": "[SUSPICIOUS]",
                "legitimate": "[LEGITIMATE]", "insufficient_evidence": "[INSUFFICIENT]"}


def log_run(record: dict) -> None:
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")


def render_report(bundle: dict, verdict: dict, grounding: dict, meta: dict) -> str:
    h = bundle.get("headers", {})
    lines = [
        f"# Phishing Triage Report — {bundle['meta']['source_file']}",
        "",
        f"**Verdict:** {verdict['verdict'].upper()}  ",
        f"**Confidence:** {verdict['confidence']:.2f}  ",
        f"**Analysed:** {meta['timestamp']}  ",
        f"**Model:** {meta['model']} (prompt {meta['prompt_version']})  ",
        f"**Latency:** {meta['latency_s']}s",
        "",
        "## Email summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| From | `{h.get('from','')}` |",
        f"| Reply-To | `{h.get('reply_to','') or '(none)'}` |",
        f"| Subject | {h.get('subject','')} |",
        f"| Date | {h.get('date','')} |",
        f"| SPF / DKIM / DMARC | {bundle['authentication']['spf']} / "
        f"{bundle['authentication']['dkim']} / {bundle['authentication']['dmarc']} |",
        f"| URLs | {len(bundle.get('urls', []))} |",
        f"| Attachments | {len(bundle.get('attachments', []))} |",
        "",
        "## Analyst assessment",
        "",
        verdict["explanation"] or "_(none returned)_",
        "",
        "## Indicators",
        "",
    ]

    if verdict["indicators"]:
        lines += ["| Severity | Indicator | Evidence field | Value | Grounding |",
                  "|---|---|---|---|---|"]
        by_field = {(d["evidence_field"], d["claimed_value"]): d["grade"]
                    for d in grounding["details"]}
        for ind in verdict["indicators"]:
            grade = by_field.get((ind["evidence_field"], ind["evidence_value"]), "?")
            mark = {"verified": "verified", "mismatched": "MISMATCH",
                    "unverifiable": "UNVERIFIED"}.get(grade, grade)
            lines.append(
                f"| {ind['severity']} | {ind['indicator']} | `{ind['evidence_field']}` "
                f"| `{ind['evidence_value'][:60]}` | {mark} |")
    else:
        lines.append("_No indicators reported._")

    lines += ["", "## Recommended actions", ""]
    for action in verdict["recommended_actions"] or ["_(none returned)_"]:
        lines.append(f"- {action}")

    lines += [
        "", "## Evidence grounding check", "",
        f"- Indicators cited: {grounding['indicator_count']}",
        f"- Verified against bundle: {grounding['verified']}",
        f"- Value mismatched: {grounding['mismatched']}",
        f"- Field unresolvable: {grounding['unverifiable']}",
    ]
    if grounding["grounding_rate"] is not None:
        lines.append(f"- Grounding rate: {grounding['grounding_rate']:.0%}")
    lines += ["", "---", "",
              "_Generated by an LLM-assisted triage tool. Verdicts are advisory "
              "and require analyst confirmation before acting._", ""]
    return "\n".join(lines)


def analyse_one(path: str, client: OllamaClient, system: str, args) -> dict | None:
    if args.from_bundle:
        with open(path, encoding="utf-8") as fh:
            bundle = json.load(fh)
    else:
        bundle = parse_eml(path)

    condensed = build_prompt_input(bundle, args.body_chars)
    user = render_user_message(condensed)
    budget = budget_report(system, user)

    if args.dry_run:
        print(f"--- {os.path.basename(path)} "
              f"(~{budget['estimated_prompt_tokens']} est. prompt tokens)")
        print(user)
        return None

    try:
        result = client.analyse(system, user, max_retries=args.retries)
    except OllamaError as exc:
        print(f"[FAIL] {os.path.basename(path)}: {exc}", file=sys.stderr)
        return None

    verdict = result["verdict"]
    grounding = check_indicators(bundle, verdict)

    meta = {
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "model": result["model"],
        "prompt_version": args.prompt_version,
        "latency_s": result["total_latency_s"],
    }

    log_run({
        **meta,
        "source_file": bundle["meta"]["source_file"],
        "raw_sha256": bundle["meta"]["raw_sha256"],
        "estimated_prompt_tokens": budget["estimated_prompt_tokens"],
        "actual_prompt_tokens": result["attempts"][-1].get("prompt_tokens"),
        "response_tokens": result["attempts"][-1].get("response_tokens"),
        "attempt_count": len(result["attempts"]),
        "json_ok_first_try": (len(result["attempts"]) == 1
                              and not result["attempts"][0]["repairs"]),
        "repairs": [r for a in result["attempts"] for r in a["repairs"]],
        "schema_problems": [p for a in result["attempts"]
                            for p in a.get("schema_problems", [])],
        "verdict": verdict,
        "grounding": {k: v for k, v in grounding.items() if k != "details"},
        "grounding_details": grounding["details"],
        "raw_response": result["attempts"][-1]["raw_content"],
    })

    if args.report_dir:
        os.makedirs(args.report_dir, exist_ok=True)
        stem = os.path.splitext(bundle["meta"]["source_file"])[0]
        report_path = os.path.join(args.report_dir, stem + ".md")
        with open(report_path, "w", encoding="utf-8") as fh:
            fh.write(render_report(bundle, verdict, grounding, meta))
    else:
        report_path = None

    icon = VERDICT_ICON.get(verdict["verdict"], "[?]")
    ground = (f"{grounding['verified']}/{grounding['indicator_count']} grounded"
              if grounding["indicator_count"] else "no indicators")
    retry_note = "" if len(result["attempts"]) == 1 else f" | {len(result['attempts'])} attempts"
    print(f"{icon:<15} {bundle['meta']['source_file']:<28} "
          f"conf={verdict['confidence']:.2f} | {ground} | "
          f"{result['total_latency_s']}s{retry_note}")
    if report_path:
        print(f"{'':<15} -> {report_path}")

    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyse an email with the local LLM.")
    ap.add_argument("target", nargs="?", help=".eml file, or .json bundle with --from-bundle")
    ap.add_argument("--dir", help="process every .eml (or .json) in this directory")
    ap.add_argument("--from-bundle", action="store_true",
                    help="input is an already-parsed Day 3 JSON bundle")
    ap.add_argument("--report-dir", help="write a Markdown report per email")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--host", default=DEFAULT_HOST)
    ap.add_argument("--prompt-version", default="v1")
    ap.add_argument("--body-chars", type=int, default=1200)
    ap.add_argument("--retries", type=int, default=1)
    ap.add_argument("--timeout", type=int, default=180)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the assembled prompt, make no LLM call")
    ap.add_argument("--check", action="store_true", help="test Ollama connectivity and exit")
    args = ap.parse_args()

    client = OllamaClient(host=args.host, model=args.model, timeout=args.timeout)

    if args.check:
        try:
            models = client.ping()
        except OllamaError as exc:
            print(f"[FAIL] {exc}")
            return 1
        print(f"[OK] {args.host} reachable.")
        print(f"      Models available: {', '.join(models) or '(none)'}")
        if not any(args.model in m for m in models):
            print(f"[WARN] '{args.model}' not in the list. Run: ollama pull {args.model}")
        return 0

    if not args.target and not args.dir:
        ap.error("give a file, or --dir, or --check")

    system = load_system_prompt(args.prompt_version)

    if args.dir:
        ext = ".json" if args.from_bundle else ".eml"
        targets = sorted(os.path.join(args.dir, f) for f in os.listdir(args.dir)
                         if f.lower().endswith(ext))
        if not targets:
            print(f"No {ext} files in {args.dir}", file=sys.stderr)
            return 1
    else:
        targets = [args.target]

    if not args.dry_run:
        try:
            client.ping()
        except OllamaError as exc:
            print(f"[FAIL] {exc}", file=sys.stderr)
            return 1

    for path in targets:
        analyse_one(path, client, system, args)

    if not args.dry_run:
        print(f"\nLogged to {LOG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
