#!/usr/bin/env python3
"""
analyze.py — command-line analysis of one or more .eml files.

Uses the same analyze_email() as the service. Each run appends a line to
logs/runs.jsonl. Also provides render_report(), which app.py imports.

Usage:
    python3 scripts/analyze.py samples/03_phish_credential.eml
    python3 scripts/analyze.py --dir samples/ --report-dir reports/
    python3 scripts/analyze.py samples/03_phish_credential.eml --dry-run
    python3 scripts/analyze.py --check
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from analyzer_core import AnalyzerError, analyze_email             # noqa: E402
from eml_parser import parse_bytes                                 # noqa: E402
from llm_client import DEFAULT_HOST, DEFAULT_MODEL, OllamaClient, OllamaError  # noqa: E402
from prompt_builder import (build_prompt_input, budget_report,     # noqa: E402
                            load_system_prompt, render_user_message)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_PATH = os.path.join(ROOT, "logs", "runs.jsonl")

VERDICT_ICON = {"phishing": "[PHISHING]", "suspicious": "[SUSPICIOUS]",
                "legitimate": "[LEGITIMATE]", "insufficient_evidence": "[INSUFFICIENT]"}


def log_run(record: dict) -> None:
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")


def render_report(bundle: dict, verdict: dict, grounding: dict, meta: dict) -> str:
    h = bundle.get("headers", {})
    lines = [
        f"# Phishing Triage Report — {bundle['meta']['source_file']}",
        "",
        f"**Verdict:** {verdict['verdict'].upper()}  ",
        f"**Confidence:** {verdict['confidence']:.2f}  ",
        f"**Analysed:** {meta['timestamp']}  ",
        f"**Model:** {meta['model']} (prompt {meta['prompt_version']})  ",
        f"**Latency:** {meta['latency_s']}s",
        "",
        "## Email summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| From | `{h.get('from','')}` |",
        f"| Reply-To | `{h.get('reply_to','') or '(none)'}` |",
        f"| Subject | {h.get('subject','')} |",
        f"| Date | {h.get('date','')} |",
        f"| SPF / DKIM / DMARC | {bundle['authentication']['spf']} / "
        f"{bundle['authentication']['dkim']} / {bundle['authentication']['dmarc']} |",
        f"| URLs | {len(bundle.get('urls', []))} |",
        f"| Attachments | {len(bundle.get('attachments', []))} |",
        "",
        "## Analyst assessment",
        "",
        verdict["explanation"] or "_(none returned)_",
        "",
        "## Indicators",
        "",
    ]

    if verdict["indicators"]:
        lines += ["| Severity | Indicator | Evidence field | Value | Grounding |",
                  "|---|---|---|---|---|"]
        by_field = {(d["evidence_field"], d["claimed_value"]): d["grade"]
                    for d in grounding["details"]}
        for ind in verdict["indicators"]:
            grade = by_field.get((ind["evidence_field"], ind["evidence_value"]), "?")
            mark = {"verified": "verified", "mismatched": "MISMATCH",
                    "unverifiable": "UNVERIFIED"}.get(grade, grade)
            lines.append(
                f"| {ind['severity']} | {ind['indicator']} | `{ind['evidence_field']}` "
                f"| `{ind['evidence_value'][:60]}` | {mark} |")
    else:
        lines.append("_No indicators reported._")

    lines += ["", "## Recommended actions", ""]
    for action in verdict["recommended_actions"] or ["_(none returned)_"]:
        lines.append(f"- {action}")

    lines += [
        "", "## Evidence grounding check", "",
        f"- Indicators cited: {grounding['indicator_count']}",
        f"- Verified against bundle: {grounding['verified']}",
        f"- Value mismatched: {grounding['mismatched']}",
        f"- Field unresolvable: {grounding['unverifiable']}",
    ]
    if grounding["grounding_rate"] is not None:
        lines.append(f"- Grounding rate: {grounding['grounding_rate']:.0%}")
    lines += ["", "---", "",
              "_Generated by an LLM-assisted triage tool. Verdicts are advisory "
              "and require analyst confirmation before acting._", ""]
    return "\n".join(lines)


def analyse_one(path: str, args) -> dict | None:
    name = os.path.basename(path)
    with open(path, "rb") as fh:
        raw = fh.read()

    if args.dry_run:
        bundle = parse_bytes(raw, source_name=name)
        system = load_system_prompt(args.prompt_version)
        user = render_user_message(build_prompt_input(bundle, args.body_chars))
        est = budget_report(system, user)["estimated_prompt_tokens"]
        print(f"--- {name} (~{est} est. prompt tokens)")
        print(user)
        return None

    try:
        result = analyze_email(raw, model=args.model, host=args.host,
                               prompt_version=args.prompt_version,
                               body_chars=args.body_chars, retries=args.retries,
                               timeout=args.timeout, source_name=name)
    except AnalyzerError as exc:
        print(f"[FAIL] {name}: {exc}", file=sys.stderr)
        return None

    bundle, verdict = result["bundle"], result["verdict"]
    grounding, meta, rel = result["grounding"], result["meta"], result["reliability"]

    log_run({
        **{k: meta[k] for k in ("timestamp", "model", "prompt_version", "latency_s",
                                "source_file", "raw_sha256", "estimated_prompt_tokens",
                                "actual_prompt_tokens", "response_tokens")},
        **rel,
        "verdict": verdict,
        "grounding": {k: v for k, v in grounding.items() if k != "details"},
        "grounding_details": grounding["details"],
        "raw_response": result["raw_response"],
    })

    report_path = None
    if args.report_dir:
        os.makedirs(args.report_dir, exist_ok=True)
        report_path = os.path.join(args.report_dir,
                                   os.path.splitext(meta["source_file"])[0] + ".md")
        with open(report_path, "w", encoding="utf-8") as fh:
            fh.write(render_report(bundle, verdict, grounding, meta))

    icon = VERDICT_ICON.get(verdict["verdict"], "[?]")
    ground = (f"{grounding['verified']}/{grounding['indicator_count']} grounded"
              if grounding["indicator_count"] else "no indicators")
    retry_note = "" if rel["attempt_count"] == 1 else f" | {rel['attempt_count']} attempts"
    print(f"{icon:<15} {meta['source_file']:<28} conf={verdict['confidence']:.2f} | "
          f"{ground} | {meta['latency_s']}s{retry_note}")
    if report_path:
        print(f"{'':<15} -> {report_path}")
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyse an email with the local LLM.")
    ap.add_argument("target", nargs="?", help=".eml file, or .json bundle with --from-bundle")
    ap.add_argument("--dir", help="process every .eml (or .json) in this directory")
    ap.add_argument("--report-dir", help="write a Markdown report per email")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--host", default=DEFAULT_HOST)
    ap.add_argument("--prompt-version", default="v1")
    ap.add_argument("--body-chars", type=int, default=1200)
    ap.add_argument("--retries", type=int, default=1)
    ap.add_argument("--timeout", type=int, default=180)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the assembled prompt, make no LLM call")
    ap.add_argument("--check", action="store_true", help="test Ollama connectivity and exit")
    args = ap.parse_args()

    client = OllamaClient(host=args.host, model=args.model, timeout=args.timeout)

    if args.check:
        try:
            models = client.ping()
        except OllamaError as exc:
            print(f"[FAIL] {exc}")
            return 1
        print(f"[OK] {args.host} reachable.")
        print(f"      Models available: {', '.join(models) or '(none)'}")
        if not any(args.model in m for m in models):
            print(f"[WARN] '{args.model}' not in the list. Run: ollama pull {args.model}")
        return 0

    if not args.target and not args.dir:
        ap.error("give a file, or --dir, or --check")


    if args.dir:
        ext = ".eml"
        targets = sorted(os.path.join(args.dir, f) for f in os.listdir(args.dir)
                         if f.lower().endswith(ext))
        if not targets:
            print(f"No {ext} files in {args.dir}", file=sys.stderr)
            return 1
    else:
        targets = [args.target]

    if not args.dry_run:
        try:
            client.ping()
        except OllamaError as exc:
            print(f"[FAIL] {exc}", file=sys.stderr)
            return 1

    for path in targets:
        analyse_one(path, args)

    if not args.dry_run:
        print(f"\nLogged to {LOG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
